### ISSUE TITLE
Disable hostname check

### ISSUE THREAD

**Issue by ldesgrange** [ansible-collections/ansible.mysql#28] opened 2020-09-17 14:43 UTC
##### SUMMARY
When connecting to MySQL with REQUIRE SSL, when the hostname check fails the task (`mysql_db`, `mysql_user`) throws an exception. It could be useful to be able to ignore the hostname check.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`community/mysql/plugins/module_utils/mysql.py`

##### ADDITIONAL INFORMATION
The hostname check can fail for self-signed certificate (dev environment), some managed MySQL provided by cloud providers seem to provide wrong certificates…

For PyMySQL, this feature request would be a mapping of the `check_hostname` options in the `ssl` argument (see [answer on stackoverflow](https://stackoverflow.com/a/46930971)).

```yaml
- name: Create a new database with name 'bobdata'
  mysql_db:
    name: bobdata
    state: present
    login_host: somehost.local
    login_user: someuser
    login_password: somepassword
    check_hostname: no
```

**Comment by Jorge-Rodriguez** [comment] 2020-09-20 07:00
@ldesgrange can you provide a way to reproduce? If we implement this we need a reliable way to test the integration.

**Comment by ldesgrange** [comment] 2020-09-20 15:38
@Jorge-Rodriguez sorry, I forgot to provide that in the ticket description. You can reproduce this issue by doing the following:
- install a debian 10 in a virtual machine (like VirtualBox)
- install mysql 8 on it:
```
wget https://dev.mysql.com/get/mysql-apt-config_0.8.15-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.15-1_all.deb
sudo apt update
sudo apt install mysql-community-server
sudo mysql -p
show variables like 'ssl%'; -- display SSL configuration, mysql has self signed certificates by default (debian's mariadb package does not), files are in /var/lib/mysql/
create user 'bob'@'%' identified by 'foobar';
grant ALL on bobdata.* to 'bob'@'%';
alter user 'bob'@'%' require ssl; -- force ssl to be used for that user
flush privileges;
```
- Run a task (from the ansible host, not from within the vm) like this (after copying `ca.pem` and `server-cert.pem` from the vm then merging them together in `server.pem`):
```
- name: Create a new database with name 'bobdata'
  community.mysql.mysql_db:
    name: bobdata
    state: present
    login_host: "vm"
    login_user: "bob"
    login_password: "foobar"
    ca_cert: "server.pem"
```
- Error message (similar one when trying to connect with the IP address instead of the hostname): `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'vm'. (_ssl.c:1108)`

**Comment by Jorge-Rodriguez** [comment] 2020-09-21 11:23
@Andersson007 I can have a go at this, but I cannot assign the issue to myself

**Comment by Andersson007** [comment] 2020-09-21 14:03
@Jorge-Rodriguez done, thanks!

**Comment by Jorge-Rodriguez** [comment] 2020-09-27 10:16
I had a look. We can implement this but it's only supported by later versions of pymysql and not by mysqldb.
Of course we can make the support for this option conditional on the underlying connector.

**Comment by Andersson007** [comment] 2020-09-28 05:29
@Jorge-Rodriguez feel free to implement.
The most important is not to affect other versions and make a **note describing dependencies** for this (minimal version in this case).
So better to test the feature locally as well with old (but supported) versions of MySQL and PyMySQL and **mysqldb** (at least that it's not become worse).

**Comment by Andersson007** [comment] 2020-09-28 05:29
I'll provide a review

**Comment by Jorge-Rodriguez** [comment] 2020-09-28 17:19
@Andersson007 I'm at a bit of a loss here. I've got the functionality ready, but I can't figure out how to plan the tests since there are three possible outcomes; success, failure because pymysql is old and failure because we're using mysqldb.
Do you have any suggestions?

**Comment by Andersson007** [comment] 2020-09-28 19:03
@Jorge-Rodriguez I think you can include CI tests in your PR only for a proper version of PyMySQL (get it from a shell and put your tests in a `block:` using `when:` if the default version in CI system is older than needed.
Test with an old version and mysqldb, at least, **locally** (if it's impossible to check which the connector is used in CI) and be sure that everything works as expected: it must NOT break or change their behavior (i.e. break backwards compatibility).
If any questions, feel free to ask

**Comment by Andersson007** [comment] 2020-09-28 19:05
e.g.
```
block:
...
when: pymysql >= ...
```
pymysql is a variable containing a connector version registered right before.
I'm not sure it's possible, it's just a suggestion that could theoretically work

**Comment by Andersson007** [comment] 2020-09-28 19:06
Also you could create a PR marked as `[WIP]` and add the tests later

**Comment by Jorge-Rodriguez** [comment] 2020-09-29 14:07
@ldesgrange Can you verify whether this is an issue with the MySQLdb connector? It appears that MySQLdb does not do hostname verification at all.

**Comment by ldesgrange** [comment] 2020-09-30 12:22
Hi, sorry for the late reply, I didn't manage to install MySQLdb on my mac. I checked on a Ubuntu computer and indeed it seems to work as is with MySQLdb. So I think you are right, MySQLdb does not check the hostname.

**Closed as completed** 2020-10-12 18:19 UTC
Labels: enhancement
