### ISSUE TITLE
why login_unix_socket can't use for remote connection?

### ISSUE THREAD

**Issue by Fanduzi** [ansible-collections/ansible.mysql#148] opened 2021-04-15 12:38 UTC
##### SUMMARY

ansible version 2.9.18
in the doc:
login_unix_socket: The path to a Unix domain socket for local connections.

My mysql only has `with grant option` for root@localhost, which means I can only ssh to the mysql server and connect via socket. But community.mysql.mysql_user's login_unix_socket only works on `connection: local`?
Unlike older versions of ansible's mysql_user module

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.9.18
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: {{ username }}
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    name: "{{ username }}"
    host: "%"
    priv: "{{ priv }}"
    update_password: on_create
    plugin: 'mysql_native_password'
    plugin_auth_string: "{{ password }}"
```

##### ACTUAL RESULTS

```paste below
{"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```

**Comment by mgedmin** [comment] 2021-06-01 12:11
The error message

> Exception message: 'database' is an invalid keyword argument for this function

suggests that your problem is caused by #116, combined with using MySQL-python instead of  PyMySQL, and it should already be fixed in #153.

**Comment by Andersson007** [comment] 2021-06-01 12:53
@mgedmin yeah, looks like it should already be fixed, thanks for pointing this out!

@Fanduzi did you install the collection manually? If yes, you should update it manually as well via ansible-galaxy. Could you please give us feedback after that? Thanks

**Comment by Fanduzi** [comment] 2021-06-02 02:12
> did you install the collection manually

did you install the collection manually? No

I am currently using mysql_user instead of community.mysql.mysql_user, the playbook running on production  is working fine so I don't plan to upgrade community.mysql.mysql_user manually, thanks, I already know what the problem is through mgedmin's answer

**Closed as completed** 2021-06-02 02:12 UTC

**Comment by Andersson007** [comment] 2021-06-02 04:55
@Fanduzi thanks for the feedback!
